environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.7

platform:
  - x64
  
os: unstable  # add desktop support

#matrix:
#  fast_finish: true

init:
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  # Miniconda setup + necessary external packages
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%  # miniconda is already installed on appveyor: https://github.com/appveyor/ci/issues/359
  - conda update conda --yes
  - conda install --yes pyqt pyyaml pyzmq numpy pytest
  - conda update --all --yes
  - pip install -r requirements.txt
  - python setup.py develop

build: off

test_script:
  - nosetests

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
