environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"

# platform:
#   - x86
#   - x64

os: unstable  # add desktop support

#matrix:
#  fast_finish: true

init:
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  # Miniconda setup + necessary external packages
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - conda update conda --yes
  - conda info -a
  - conda install --yes pyqt pyyaml pyzmq numpy pytest
  - pip install -e .
  - conda list

build: off

test_script:
  - nosetests

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
