producer_sim :
    DAQ0 :
        kind : example_producer_sim
        delay : 0.2
        backend : tcp://127.0.0.1:5500
        
    DAQ1 :
        kind : example_producer_sim
        delay : 0.2
        backend : tcp://127.0.0.1:5501

converter :
    CON0 :
        kind : example_converter
        frontend : tcp://127.0.0.1:5500
        backend : tcp://127.0.0.1:5600
        threshold : 8
    CON1 :
        kind : forwarder
        frontend : tcp://127.0.0.1:5500
        backend : tcp://127.0.0.1:5601
        max_cpu_load : 30
    CON2 :
        kind : bidirectional_converter
        frontend : tcp://127.0.0.1:5500
        backend : tcp://127.0.0.1:5602
    CON3 :
        kind : position_correlator
        frontend :
          - tcp://127.0.0.1:5500
          - tcp://127.0.0.1:5501
        backend : tcp://127.0.0.1:5603   


receiver :
    DUT1 :
        kind : example_receiver
        frontend : tcp://127.0.0.1:5600
        
    DUT2 :
        kind : bidirectional_receiver
        frontend : tcp://127.0.0.1:5602
 #   DUT2 :
 #       kind : example_receiver
  #      frontend : tcp://127.0.0.1:5602
