producer :
    DAQ0 :
        send_address : tcp://127.0.0.1:5500
        data_type : test
    DAQ1 :
        send_address : tcp://127.0.0.1:5501
        data_type : test

converter :
    DUT0 :
        data_type : example_converter
        receive_address : tcp://127.0.0.1:5500
        send_address : tcp://127.0.0.1:5680
        max_cpu_load : 30
        threshold : 8
    DUT1 :
         data_type : forwarder
         receive_address : tcp://127.0.0.1:5680
         send_address : tcp://127.0.0.1:5581
    DUT1 :
         data_type : forwarder
         receive_address : tcp://127.0.0.1:5500
         send_address : tcp://127.0.0.1:5582
     
receiver :
    DUT0 :
        data_type : example_receiver
        receive_address : tcp://127.0.0.1:5680
   # DUT1 :
    #    data_type : example_receiver
     #   receive_address : tcp://127.0.0.1:5581
   # DUT2 :
    #    data_type : example_receiver
     #   receive_address : tcp://127.0.0.1:5582