name: Build wheels

on: workflow_dispatch
  # release

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{matrix.runs-on}}
    strategy:
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: windows-intel
            runs-on: windows-latest
          - os: macos-intel
            # macos-15-intel is the last x86_64 runner
            runs-on: macos-15-intel
          - os: macos-arm
            runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
        
    - name: Build hweels
      uses: pypa/cibuildwheel@v3.4.0
      env:
        # Build CPython only
        CIBW_BUILD: cp*
        # Skip Python 3.8, 32-bit, and free-threaded builds
        CIBW_SKIP: "cp38-* *-win32 *-manylinux_i686 cp3??t-*"

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
